# Generated by Django 3.1 on 2021-07-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shorts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('brand', models.CharField(max_length=250, verbose_name='Бренд')),
                ('gender', models.CharField(max_length=250, verbose_name='Пол')),
                ('model', models.CharField(max_length=250, verbose_name='Модель')),
                ('color', models.CharField(max_length=250, verbose_name='Цвет')),
                ('size', models.CharField(max_length=250, verbose_name='Размер')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('brand', models.CharField(max_length=250, verbose_name='Бренд')),
                ('gender', models.CharField(max_length=250, verbose_name='Пол')),
                ('model', models.CharField(max_length=250, verbose_name='Модель')),
                ('color', models.CharField(max_length=250, verbose_name='Цвет')),
                ('size', models.CharField(max_length=250, verbose_name='Размер')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('brand', models.CharField(max_length=250, verbose_name='Бренд')),
                ('gender', models.CharField(max_length=250, verbose_name='Пол')),
                ('model', models.CharField(max_length=250, verbose_name='Модель')),
                ('color', models.CharField(max_length=250, verbose_name='Цвет')),
                ('size', models.CharField(max_length=250, verbose_name='Размер')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mikey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('brand', models.CharField(max_length=250, verbose_name='Бренд')),
                ('gender', models.CharField(max_length=250, verbose_name='Пол')),
                ('model', models.CharField(max_length=250, verbose_name='Модель')),
                ('color', models.CharField(max_length=250, verbose_name='Цвет')),
                ('size', models.CharField(max_length=250, verbose_name='Размер')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
