# Generated by Django 3.1 on 2021-07-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210701_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikey',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='short',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
