# Generated by Django 3.1 on 2021-07-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210703_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikey',
            name='color',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='color',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='short',
            name='color',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Цвет'),
        ),
    ]
