# Generated by Django 3.1 on 2021-07-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210704_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_at',
            new_name='order_date',
        ),
    ]
